# Generated by Django 5.0.7 on 2024-08-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['time_created']},
        ),
    ]
